server:
  port: 8001
spring:
  application:
    name: eureka-openfegin-client-consumer
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      # 单节点
      # defaultZone: http://127.0.0.1:8761/eureka
      # 多节点
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/,http://eureka-server-3:8763/eureka/
feign:
  client:
    config:
      default: # 客户端默认配置
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000 # 读取超时时间

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.maxqiu.demo.service.ProviderService: debug