server:
  port: 40001 # 端口
spring:
  application:
    name: gateway # 服务模块名称，根据模块名称填写
  cloud:
    nacos:
      server-addr: nacos:8848 # nacos服务端地址（注册中心 和 配置中心 地址）
      discovery:
        enabled: true # 是否启用注册中心。默认：true
        server-addr: ${spring.cloud.nacos.server-addr} # 注册中心地址，如果和配置中心地址不一样，可单独配置
        namespace: # 服务所在命名空间ID，一般用于隔离不同项目的服务。默认：
        group: DEFAULT_GROUP # 服务所在分组，一般用于隔离不同环境的服务。默认：DEFAULT_GROUP
        service: ${spring.application.name} # 注册的服务名称。默认：${spring.application.name}
        weight: 1 # 权重
    gateway:
      routes:
        - id: server
          uri: lb://server
          predicates:
            - Path=/**
