server:
  port: 40301 # 端口
spring:
  application:
    name: feign # 服务模块名称，根据模块名称填写
  cloud:
    nacos:
      server-addr: nacos:8848 # nacos服务端地址（注册中心 和 配置中心 地址）
      discovery:
        enabled: true # 是否启用注册中心。默认：true
        server-addr: ${spring.cloud.nacos.server-addr} # 注册中心地址，如果和配置中心地址不一样，可单独配置
        namespace: # 服务所在命名空间ID，一般用于隔离不同项目的服务。默认：
        group: DEFAULT_GROUP # 服务所在分组，一般用于隔离不同环境的服务。默认：DEFAULT_GROUP
        service: ${spring.application.name} # 注册的服务名称。默认：${spring.application.name}
        weight: 1 # 权重
# Feign配置
feign:
  #  compression: # 压缩设置（暂时不要开启，目前版本还有bug）
  #    request: # 请求压缩
  #      enabled: false # 是否启用。默认：false
  #      mime-types: # 支持的mime类型。示例即默认配置
  #        - "text/xml"
  #        - "application/xml"
  #        - "application/json"
  #      min-request-size: 2048 # 启用压缩的最小内容大小。
  #    response: # 响应压缩
  #      enabled: false # 是否启用。默认：false
  #      useGzipDecoder: false # 启用gzip解码器来解码gzip响应。默认false
  client:
    config:
      default: # feign客户端全局默认配置
        loggerLevel: FULL # 显示全部请求与返回信息，详见：feign.Logger.Level
        connectTimeout: 1000 # 连接超时时间，单位毫秒。默认：10000
        readTimeout: 3000 # 读取超时时间，单位毫秒。默认：60000
  autoconfiguration:
    jackson:
      enabled: true # Spring Data Support。默认：false
# 日志配置
logging:
  level:
    com.maxqiu.demo.**.feign.**: debug # 指定Feign接口日志级别为debug（建议仅开发环境启用）
