server:
  port: 9001
spring:
  application:
    name: nacos-client-provider
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'