server:
  port: 8761
spring:
  application:
    name: eureka-server-1
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server-2:8762/eureka/