server:
  port: 8401

spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: sentinel-server:8080 #配置Sentinel dashboard地址
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'